### ISSUE TITLE
Add more configurations to be set in config.yml file

### ISSUE THREAD

**Issue by manas11** [IRIS-NITK/puptime#1]
`config.yml` file stores configurations related to which hosts to monitor, protocol etc.

Currently, it has following configs to be set: 
```
  group: test1
                name: blabla
                interval: 10s
                options:
                        url: https://blabla@blabla.com/
                        request-method: GET
                        response-code: 200
                        follow-redirect: true
                type: HTTP

```

Add more configurations like: 

- [ ] Timeout

- [ ] ssl_verifypeer

- [ ] ssl_verifyhost

User should be able to set these in the config.yml file. After, setting this, [Line 55 lib/http.rb](https://github.com/IRIS-NITK/puptime/blob/3fac344968c58160a7bb53065373412736ec48f2/lib/puptime/service/http.rb#L55) should be able to parse these options
